In [1]:
import pandas as pd 
import numpy as np

In [17]:
df = pd.read_csv('/Users/danialmendigali/jupyter-datascience/Pandas/data set /insurance.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [7]:
df.tail()

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [8]:
df['sex'].value_counts()

sex
male      676
female    662
Name: count, dtype: int64

In [9]:
df['smoker'].value_counts()

smoker
no     1064
yes     274
Name: count, dtype: int64

In [18]:
df['type_bmi'] = np.where(
    df['bmi'].between(20, 30), 'low',
    np.where(df['bmi'].between(31, 40), 'middle', 'high')
)

In [20]:
df.head(5)

   age     sex     bmi  children smoker     region      charges type_bmi
0   19  female  27.900         0    yes  southwest  16884.92400      low
1   18    male  33.770         1     no  southeast   1725.55230   middle
2   28    male  33.000         3     no  southeast   4449.46200   middle
3   33    male  22.705         0     no  northwest  21984.47061      low
4   32    male  28.880         0     no  northwest   3866.85520      low

In [21]:
df['rank_bmi'] = df['bmi'].rank()

In [22]:
df.head(5)

,age,sex,bmi,children,smoker,region,charges,type_bmi,rank_bmi
0,19,female,27.900,0,yes,southwest,16884.92400,low,459.0
1,18,male,33.770,1,no,southeast,1725.55230,middle,943.5
2,28,male,33.000,3,no,southeast,4449.46200,middle,879.5
3,33,male,22.705,0,no,northwest,21984.47061,low,124.0
4,32,male,28.880,0,no,northwest,3866.85520,low,541.5

In [23]:
df['new_region'] = df['region'].apply(lambda x: x.upper())

In [24]:
df.tail()

,age,sex,bmi,children,smoker,region,charges,type_bmi,rank_bmi,new_region
1333,50,male,30.97,3,no,northwest,10600.5483,high,722.0,NORTHWEST
1334,18,female,31.92,0,no,northeast,2205.9808,middle,796.0,NORTHEAST
1335,18,female,36.85,0,no,southeast,1629.8335,middle,1124.0,SOUTHEAST
1336,21,female,25.80,0,no,southwest,2007.9450,low,302.0,SOUTHWEST
1337,61,female,29.07,0,yes,northwest,29141.3603,low,562.5,NORTHWEST

In [34]:
gr1 = df.groupby(['sex', 'smoker']).agg({
    'bmi' : ['min', 'max']
})

In [36]:
gr1

                  bmi
                  min    max
sex    smoker
female no      16.815  48.07
       yes     17.195  47.60
male   no      15.960  53.13
       yes     17.290  52.58

In [40]:
df.sort_values(by='bmi', ascending=False)

,age,sex,bmi,children,smoker,region,charges,type_bmi,rank_bmi,new_region
1317,18,male,53.130,0,no,southeast,1163.46270,high,1338.0,SOUTHEAST
1047,22,male,52.580,1,yes,southeast,44501.39820,high,1337.0,SOUTHEAST
847,23,male,50.380,1,no,southeast,2438.05520,high,1336.0,SOUTHEAST
116,58,male,49.060,0,no,southeast,11381.32540,high,1335.0,SOUTHEAST
286,46,female,48.070,2,no,northeast,9432.92530,high,1334.0,NORTHEAST
...,...,...,...,...,...,...,...,...,...,...
1286,28,female,17.290,0,no,northeast,3732.62510,high,6.0,NORTHEAST
412,26,female,17.195,2,yes,northeast,14455.64405,high,4.0,NORTHEAST
1226,38,male,16.815,2,no,northeast,6640.54485,high,2.5,NORTHEAST
428,21,female,16.815,1,no,northeast,3167.45585,high,2.5,NORTHEAST
172,18,male,15.960,0,no,northeast,1694.79640,high,1.0,NORTHEAST

In [41]:
df.sort_index()

,age,sex,bmi,children,smoker,region,charges,type_bmi,rank_bmi,new_region
0,19,female,27.900,0,yes,southwest,16884.92400,low,459.0,SOUTHWEST
1,18,male,33.770,1,no,southeast,1725.55230,middle,943.5,SOUTHEAST
2,28,male,33.000,3,no,southeast,4449.46200,middle,879.5,SOUTHEAST
3,33,male,22.705,0,no,northwest,21984.47061,low,124.0,NORTHWEST
4,32,male,28.880,0,no,northwest,3866.85520,low,541.5,NORTHWEST
...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,high,722.0,NORTHWEST
1334,18,female,31.920,0,no,northeast,2205.98080,middle,796.0,NORTHEAST
1335,18,female,36.850,0,no,southeast,1629.83350,middle,1124.0,SOUTHEAST
1336,21,female,25.800,0,no,southwest,2007.94500,low,302.0,SOUTHWEST
1337,61,female,29.070,0,yes,northwest,29141.36030,low,562.5,NORTHWEST

In [48]:
df.loc[
    (df['sex'] == 'male') & 
    (df['age'] > 60) & 
    (df['bmi'] > 30) & 
    (df['smoker'] == 'no') &
    (df['children'] == 0)
]

,age,sex,bmi,children,smoker,region,charges,type_bmi,rank_bmi,new_region
170,63,male,41.470,0,no,southeast,13405.39030,high,1281.0,SOUTHEAST
190,61,male,31.570,0,no,southeast,12557.60530,middle,766.5,SOUTHEAST
335,64,male,34.500,0,no,southwest,13822.80300,middle,998.0,SOUTHWEST
341,62,male,30.020,0,no,northwest,13352.09980,high,635.5,NORTHWEST
343,63,male,36.765,0,no,northeast,13981.85035,middle,1120.0,NORTHEAST
493,61,male,43.400,0,no,southwest,12574.04900,high,1308.0,SOUTHWEST
534,64,male,40.480,0,no,southeast,13831.11520,high,1262.0,SOUTHEAST
550,63,male,30.800,0,no,southwest,13390.55900,high,706.5,SOUTHWEST
635,64,male,38.190,0,no,northeast,14410.93210,middle,1193.0,NORTHEAST
642,61,male,33.915,0,no,northeast,13143.86485,middle,954.5,NORTHEAST
722,62,male,37.400,0,no,southwest,12979.35800,middle,1160.0,SOUTHWEST
752,64,male,37.905,0,no,northwest,14210.53595,middle,1176.0,NORTHWEST
830,63,male,33.100,0,no,southwest,13393.75600,middle,885.5,SOUTHWEST
894,62,male,32.110,0,no,northeast,13555.00490,middle,808.0,NORTHEAST
944,62,male,39.930,0,no,southeast,12982.87470,middle,1246.0,SOUTHEAST
1034,61,male,38.380,0,no,northwest,12950.07120,middle,1198.5,NORTHWEST
1071,63,male,31.445,0,no,northeast,13974.45555,middle,758.5,NORTHEAST
1322,62,male,38.830,0,no,southeast,12981.34570,middle,1207.0,SOUTHEAST
1325,61,male,33.535,0,no,northeast,13143.33665,middle,924.0,NORTHEAST